import Head from "next/head";
import styles from "../styles/Home.module.css";
import BasicAppBar from "../components/organims/headers/basicHeader";
import BasicFooter from "../components/organims/footers/basicFooter";
import Main from "./main";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title> T2 créditos </title>{" "}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BasicAppBar />
        <Main />
        <BasicFooter />
      </main>
    </div>
  );
}
